export const POPULATE_EVENTS = 'POPULATE_EVENTS';
export const ADD_ACCOUNT_TYPE = 'ADD_ACCOUNT_TYPE';
export const SET_EVENT_DETAIL = 'SET_EVENT_DETAIL';
export const SET_PAGE = 'SET_PAGE';
export const POPULATE_CENTERS = 'POPULATE_CENTERS';
export const SET_CENTER_DETAILS = 'SET_CENTER_DETAILS';